[build]
  publish = "."

[[redirects]]
  from = "/images/*"
  to = "https://raw.githubusercontent.com/srikanth1815101/wishes/pilot/static/images/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
